
load: False
to_load: ""
load_path: "${pc_config.model_save_path}model_archives/"
save_path: "${pc_config.model_save_path}model_saves/"
save_predictions_path:  "${pc_config.model_save_path}prediction_saves/"
save_predictions: False
save_targets: False
is_save_anchors: False

collate_fn: "list"

optimizer: "SGD" # can be SGD or Adam
scheduler: "reduce_on_plateau" #"linear_warmup_cosine_annealing_lr" 
scheduler_patience: 2
lr_scheduler_interval: "epoch"
lr_scheduler_frequency: 2

learning_rate: 0.001
momentum: 0.9
weight_decay: 0.0001
class_loss_reduction: "sum" # can be sum or mean
class_loss_factor: 1

class_metric: False
log_heatmap: False
log_fcos_inside: False
calcul_metric_train_each_nb_batch: 3
save_each_epoch: 10

pretrained: false

# TODO put away all that follow

enable_unknown: False
enable_semantics_classes: False
enable_semantics_centerness: False

prediction_from_rpn: False

my_scoring_function_filter: False # careful ! change param just beside bot #change scoring for eliminating boxes from sqrt(centerness * classe) to (centerness - 1)(classe - 1)  
object_score_threshold: 0.6

nms_iou_threshold: 0.5
threshold_score_centerness_unknown: 0.5
threshold_score_remove: 0.2
threshold_score_good: 0.5

validation_calculate_losses: True
test_calculate_losses: False

#To remove:
mode: ""
