defaults:    
    - default_model
    - rpn: rpn
    
name: "faster_rcnn"
pretrained: false
only_rpn: false
freeze_backbone: false

# Config params
ai_iou: false
ai_oro: false
perfect_oro: false 
keep_background: false
filter_with_oro: false
open_low_known_classes_as_unknown: false

training:
    freeze_classifier: false

