defaults:
    - _self_
    - model: fcos
    - pc_config: laptop_corentin
    - dataset: bdd100k
    - metrics: metrics
    - override hydra/sweeper: optuna
    - override hydra/launcher: joblib



debug: False

test_on_train: True
test_on_val: True
test_on_test: True

max_epochs: 10
combine_classes: False
show_image: True  #show the image

# Speed parameters
accumulate_gradient_nb_batch: 16
precision_float: "16-mixed"
check_val_every_n_epoch: 1
early_stopping: False
early_stopping_monitor: "val_coverage"

is_log: false


sort_prediction:
    threshold_upper_score: 0.5
    threshold_under_score_minimum: 0.2
    classes_as_known: []
    keep_low_known_classes_as_unknown: False 
    remove_under_oro_score: False
    oro_score_threshold: 0.5
    nms_unknown_inside_known: True
    nms_iou_threshold: 0.5

    alpha_bce: 1
    alpha_iou: 1
    alpha_centerness: 1

logger:
    log_every_n_steps: 1
    wandb_offline: False 
    wandb_on: True
    project_name: "OpenWorldObjectDetection"

dataloader:
    batch_size: ${pc_config.dataloader.batch_size}
    num_workers: ${pc_config.dataloader.num_workers}
    shuffle_in_training: True

hydra:
    sweeper:
        direction: maximize
        study_name: alpha_scores 
        n_trials: 10
        n_jobs: 4
        params:
            sort_prediction.alpha_iou: range(0, 1, step=0.1)
            sort_prediction.alpha_centerness: range(0, 1, step=0.1)
            sort_prediction.alpha_bce: range(0, 1, step=0.1)

