defaults:    
    - default_dataset

name: "carla"
path: "${pc_config.dataset_path}carla/11-10"
shuffle: False
image_width: 1820
image_height: 1240
image_resize_width: 1820 #640 # 1280 #1280
image_resize_height: 1240 #512 # 1024 #768
max_size: 155
train_max_size: 100
classes_names: ['pedestrians', 'cars', 'trucks', 'bicycles', 'motorcycles', 'traffic_signs', 'traffic_light', 'riders', 'buses', 'roads', "sidewalks", "building", "walls", "poles", "sky", "vegetation", "static", "dynamic", "other", "roadLines", "ground", "rail_track", "water", 'poles', 'fences', 'bridge', 'guard_rail', 'terrain', 'cyclists']
